VOC_LABELS = [
    "aeroplane",
    "bicycle",
    "bird",
    "boat",
    "bottle",
    "bus",
    "car",
    "cat",
    "chair",
    "cow",
    "diningtable",
    "dog",
    "horse",
    "motorbike",
    "person",
    "pottedplant",
    "sheep",
    "sofa",
    "train",
    "tvmonitor",
]
VOC_BETTER_LABELS = [
    "aeroplane",
    "bicycle",
    "bird avian",
    "boat",
    "bottle",
    "bus",
    "car",
    "cat",
    "chair seat",
    "cow",
    "diningtable",
    "dog",
    "horse",
    "motorbike",
    "person with clothes,people,human",
    "pottedplant",
    "sheep",
    "sofa",
    "train",
    "tvmonitor screen",
]

VOC_SIMILAR_LABELS = [
    ["aeroplane", "plane"],
    ["bicycle","bike"], # bike
    ["bird", "avian"],
    ["boat"],
    ["bottle"], # cup, 高脚杯
    ["bus"],
    ["car"],
    ["cat"],
    ["chair seat"],
    ["cow"],
    ["diningtable", "table"],
    ["dog"],
    ["horse"],
    ["motorbike", "motorcycle"],
    ["person", "person with clothes","people","human"],
    ["pottedplant"],  # "flowerpot"
    ["sheep","goat"],
    ["sofa"],
    ["train"],
    ["tvmonitor","screen", "monitor"],
]

COCO_LABELS = [
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "dining table",
    "toilet",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
]

COCO_BETTER_LABELS = [
    "person with clothes,people,human",
    "bicycle",
    "car",
    "motorbike",
    "aeroplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird avian",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack,bag",
    "umbrella,parasol",
    "handbag,purse",
    "necktie",
    "suitcase",
    "frisbee",
    "skis",
    "sknowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "dessertspoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair seat",
    "sofa",
    "pottedplant",
    "bed",
    "diningtable",
    "toilet",
    "tvmonitor screen",
    "laptop",
    "mouse",
    "remote control",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hairdrier,blowdrier",
    "toothbrush",
]

def get_coco_better_labels_in_alphabet_order():
    ref=dict(zip(COCO_LABELS,COCO_BETTER_LABELS))
    coco_labels=sorted(COCO_LABELS)
    coco_better_labels=[]
    for k in coco_labels:
        coco_better_labels.append(ref[k])
    return coco_labels,coco_better_labels

BACKGROUND_LABEL = [
    "ground",
    "land",
    "grass",
    "tree",
    "building",
    "wall",
    "sky",
    "lake",
    "water",
    "river",
    "sea",
    "railway",
    "railroad",
    "helmet",
    "cloud",
    "house",
    "mountain",
    "ocean",
    "road",
    "rock",
    "street",
    "valley",
    "bridge",
]
